### ISSUE TITLE
Requesting access to the saved fine tuned NLI logical fallacy models

### ISSUE THREAD

**Issue by vishprivenkat** [causalNLP/logical-fallacy#2]
Hi, 
This is Vishnu Priya, a student worker at ISI. I m working on a research project that is headed by Fillip Ilievski, for which a good understanding of Logical Fallacies is required, as described in your work Logical Fallacy Detection (arXiv:2202.13758, 2022).  

While trying to run the fine-tuned models as described in the research work, I m encountering a 404 error while trying to download the saved NLI models (https://drive.google.com/uc?id=1_zIduJngoU5sMbmjymrUPamWgtfgp2xB&export=download), and I'd like to request access to the saved fine tuned NLI logical fallacy models for the same. 

Thank You 
Vishnu

**Comment by LifeIsStrange** [comment]
@labhinav friendly ping

**Comment by labhinav** [comment]
here are the links to the saved models https://drive.google.com/drive/u/1/folders/13icpZY_HNemv9Da14fYEyw8EfoxEvKQZ
