### ISSUE TITLE
Structure aware premise

### ISSUE THREAD

**Issue by jw9603** [causalNLP/logical-fallacy#4]
Hi, 
I found your paper quite interesting. 

Could you let me know where I can find the code that sets the mask for tokens when converting the edu_all.csv file to edu_{train,valid,test}.csv files?"

Thanks.

**Comment by hieuchi911** [comment]
- I believe [`mask_out_content`](https://github.com/causalNLP/logical-fallacy/blob/c84856486b6f113f332a9273b6f79d5395c99720/codes_for_models/experiments_round2/remove_content_words.py#L93) is the function that distils the texts to create the MSK.
- To generate the `edu_{train,valid,test}.csv` files, I think they run script from the same file ([`codes_for_models.experiments_round2.remove_content_words`](https://github.com/causalNLP/logical-fallacy/blob/c84856486b6f113f332a9273b6f79d5395c99720/codes_for_models/experiments_round2/remove_content_words.py#L266)), passing paths to `edu_all.csv` to `path` argument

**Comment by jw9603** [comment]
Thank you for good information.

**Comment by jw9603** [comment]
Can you tell me where the additional structure-Aware hypothesis part is masked?

**Comment by hieuchi911** [comment]
According to the last paragraph in section 3.2 in their paper, it's a combination of manual work of adapting from external websites about logical fallacies and masking. You can find the masking in their code and [here](https://github.com/causalNLP/logical-fallacy/blob/c84856486b6f113f332a9273b6f79d5395c99720/codes_for_models/experiments_round2/logicedu.py#L102C14-L106) and then [here](https://github.com/causalNLP/logical-fallacy/blob/c84856486b6f113f332a9273b6f79d5395c99720/codes_for_models/experiments_round2/library.py#L18)

**Comment by jw9603** [comment]
Thank you I confirmed that part.

Additionally, The masked part changes to 'A', 'B', ....  Is there an MLM loss that matches this part?

**Comment by labhinav** [comment]
We do not use an MLM loss as we are not trying to predict the masked content, rather we use masks to remove semantic information from the inputs. Hope this helps!

**Comment by jw9603** [comment]
To check whether the 'text' below in remove_content_words.py is properly masked, I ran "python remove_content_words.py" without providing any arguments, and 'text' appears as is. 

What is the problem? 

I think it's because I didn't give the "model" argument, is that correct?

If that's correct, what should I give as "model"?

Thank you every time.

**Comment by labhinav** [comment]
you can use any sentence transformers model, such as sentence-transformers/all-MiniLM-L12-v2

**Comment by jw9603** [comment]
if __name__ == '__main__':
    # word_bank = []
    stanza.download('en', processors='tokenize,mwt,pos,lemma,ner,depparse,coref')
    stanza.install_corenlp()

    # nlp = stanza.Pipeline(lang='en', processors='tokenize,mwt,pos,lemma', use_gpu=True)
    en = spacy.load('en_core_web_sm')
    sw_spacy = en.Defaults.stop_words
    parser = argparse.ArgumentParser()
    logger = get_logger(level='WARN')
    parser.add_argument("-p", "--path", help="path for input csv file")
    parser.add_argument("-a", "--article_col_name", help="column which contains the main text")
    parser.add_argument("-m", "--model", help="sentence transformer model")
    args = parser.parse_args()
    model = SentenceTransformer(args.model)
    print(model)
    client = CoreNLPClient(
        annotators=['tokenize', 'ssplit', 'pos', 'lemma', 'ner', 'parse', 'depparse', 'coref'], timeout=30000)
    # update_csv_with_masked_content(args.path, args.article_col_name, model, client)
    # print(word_bank) pickle.dump(word_bank, open("../../data/word_bank.pkl", "wb"))
    text = "Senator Randall isn't lying when she says she cares about her constituents—she wouldn't lie to people she cares about."
    print(mask_out_content(text, model, client, debug=True))
    
  
  This code is the main statement of the "remove_contents_word.py" code and I am testing whether masking occurs in the text. As you said, I gave a command like "python remove_content_words.py -m all-MiniLM-L12-v2", but no masking occurs in the text. What's the problem?
  
  
<img width="941" alt="image" src="https://github.com/causalNLP/logical-fallacy/assets/70795645/638d936f-129e-43ab-ac00-881adfe980b3">

**Comment by jw9603** [comment]
It seems like the "mask_out_content" function is used to mask out a random text in remove_content_words.py. 

there are try and except statements in the **mask_out_content function**, but it keeps falling into the except statement.

I think it is missing except because of the annotate in the ann=client.annotate(text) part.
__________________________________________________________________________
2023-12-10 19:29:31 INFO: Writing properties to tmp file: corenlp_server-8b1f20b582ee4cee.props
Writing properties to tmp file: corenlp_server-8b1f20b582ee4cee.props
Traceback (most recent call last):
  File "/home/jiwon/anaconda3/envs/cycle/lib/python3.9/site-packages/stanza/server/client.py", line 134, in start
    sock.bind((self.host, self.port))
OSError: [Errno 98] Address already in use

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jiwon/remove_content_words.py", line 382, in <module>
    print(client.annotate(text))
  File "/home/jiwon/anaconda3/envs/cycle/lib/python3.9/site-packages/stanza/server/client.py", line 536, in annotate
    r = self._request(text.encode('utf-8'), request_properties, reset_default, **kwargs)
  File "/home/jiwon/anaconda3/envs/cycle/lib/python3.9/site-packages/stanza/server/client.py", line 446, in _request
    self.ensure_alive()
  File "/home/jiwon/anaconda3/envs/cycle/lib/python3.9/site-packages/stanza/server/client.py", line 206, in ensure_alive
    self.start()
  File "/home/jiwon/anaconda3/envs/cycle/lib/python3.9/site-packages/stanza/server/client.py", line 141, in start
    raise PermanentlyFailedException("Error: unable to start the CoreNLP server on port %d "
stanza.server.client.PermanentlyFailedException: Error: unable to start the CoreNLP server on port 9000 (possibly something is already running there)
__________________________________________________________________________
![image](https://github.com/causalNLP/logical-fallacy/assets/70795645/3cc06417-9cfe-4c93-8dfc-2774515bfb45)

How can I specifically use **remove_content_words.py?**

Thank You!

**Comment by labhinav** [comment]
the error is because you already have something running on the port 9000. Please check for any running processes on that port and kill them before running this

**Comment by jw9603** [comment]
Thanks for your reply!
